# Generated by Django 5.1.2 on 2024-12-08 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllCourses",
            fields=[
                (
                    "course_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("courseName", models.CharField(max_length=255, unique=True)),
                ("unit", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("theory_course", "theory course"),
                            ("basic_course", "basic course"),
                            ("practical_course", "practical course"),
                            ("elective_course", "elective course"),
                            ("public_course", "public course"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
            options={
                "db_table": "AllCourses",
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "rule_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("entry_rule", "entry_rule")], max_length=30
                    ),
                ),
                ("values", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Rule",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "c_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("teacherName", models.CharField(max_length=255)),
                ("isExperimental", models.BooleanField()),
                (
                    "class_time1",
                    models.CharField(
                        choices=[
                            ("شنبه", "شنبه"),
                            ("یکشنبه", "یکشنبه"),
                            ("دوشنبه", "دوشنبه"),
                            ("سه شنبه", "سه شنبه"),
                            ("چهارشنبه", "چهارشنبه"),
                            ("پنجشنبه", "پنجشنبه"),
                            ("جمعه", "جمعه"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "class_time2",
                    models.CharField(
                        choices=[
                            ("شنبه", "شنبه"),
                            ("یکشنبه", "یکشنبه"),
                            ("دوشنبه", "دوشنبه"),
                            ("سه شنبه", "سه شنبه"),
                            ("چهارشنبه", "چهارشنبه"),
                            ("پنجشنبه", "پنجشنبه"),
                            ("جمعه", "جمعه"),
                        ],
                        max_length=255,
                    ),
                ),
                ("class_start_time", models.TimeField()),
                ("class_end_time", models.TimeField()),
                ("exam_date", models.DateField()),
                ("exam_start_time", models.TimeField()),
                ("exam_end_time", models.TimeField()),
                ("capacity", models.IntegerField()),
                ("registered", models.IntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.allcourses",
                    ),
                ),
            ],
            options={
                "db_table": "Course",
            },
        ),
        migrations.CreateModel(
            name="Coreq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coreq_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="is_coreq_of",
                        to="course.allcourses",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coreqs_for",
                        to="course.allcourses",
                    ),
                ),
            ],
            options={
                "db_table": "Coreq",
                "unique_together": {("course", "coreq_course")},
            },
        ),
        migrations.CreateModel(
            name="Prereq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prereqs_for",
                        to="course.allcourses",
                    ),
                ),
                (
                    "prereq_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="is_prereq_of",
                        to="course.allcourses",
                    ),
                ),
            ],
            options={
                "db_table": "Prereq",
                "unique_together": {("course", "prereq_course")},
            },
        ),
        migrations.CreateModel(
            name="CourseRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.rule"
                    ),
                ),
            ],
            options={
                "db_table": "CourseRule",
                "unique_together": {("course", "rule")},
            },
        ),
    ]
