<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-11-10 10:45
=======
# Generated by Django 5.1.2 on 2024-11-11 10:51
>>>>>>> feature/course/create

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0010_alter_course_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="type",
            field=models.CharField(
                choices=[
                    ("basic_course", "basic course"),
<<<<<<< HEAD
                    ("public_course", "public course"),
                    ("specialy_course", "specialy course"),
                    ("elective_course", "elective course"),
=======
                    ("elective_course", "elective course"),
                    ("public_course", "public course"),
                    ("specialy_course", "specialy course"),
>>>>>>> feature/course/create
                ],
                max_length=30,
            ),
        ),
    ]
