# Generated by Django 5.1.2 on 2024-11-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0013_alter_course_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="type",
            field=models.CharField(
                choices=[
                    ("public_course", "public course"),
                    ("basic_course", "basic course"),
                    ("specialy_course", "specialy course"),
                    ("elective_course", "elective course"),
                ],
                max_length=30,
            ),
        ),
    ]
