# Generated by Django 5.1.2 on 2024-11-06 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("support", "support"),
                            ("admin", "admin"),
                            ("academicassistant", "academicassistant"),
                            ("student", "student"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
            options={
                "db_table": "User",
            },
        ),
    ]
