# Generated by Django 5.1.2 on 2024-11-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("student", "student"),
                    ("admin", "admin"),
                    ("support", "support"),
                    ("academicassistant", "academicassistant"),
                ],
                max_length=30,
            ),
        ),
    ]
