version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '0146'
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: ./Back
      dockerfile: Dockerfile
    container_name: my-django
    environment:
      DEBUG: '1'
      DATABASE_NAME: mydatabase
      DATABASE_USER: admin
      DATABASE_PASSWORD: '0146'
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    ports:
      - "8000:8000"
    
    volumes:
      - ./Back:/app
    
    depends_on:
      - postgres

volumes:
  postgres_data:
